# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-09 04:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prontuarios', '0002_auto_20171009_0405'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalpaciente',
            old_name='user_ptr',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='user_ptr',
        ),
        migrations.AddField(
            model_name='consulta',
            name='paciente',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='prontuarios.Paciente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalconsulta',
            name='paciente',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='prontuarios.Paciente'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
