# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-09 04:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prontuarios', '0004_auto_20171009_0440'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalpaciente',
            old_name='user',
            new_name='user_ptr',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='user',
        ),
        migrations.AddField(
            model_name='paciente',
            name='user_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
